/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasdistribuidos_matricula_danielrivera;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class RegistrarEmpleado extends javax.swing.JFrame {

    public int indice;   
    // Instancio la clase
    private Conexion objConexion = new Conexion();
    /**
     * Creates new form Register
     */
    public RegistrarEmpleado() {
        initComponents();
        setSize(726,558);//Para dar tamaño a la ventana
        setResizable(false);//Para que no se pueda retirar
        setLocationRelativeTo(null);//Para que aparezca a la mitad de la pantalla
        setTitle("Registrar Empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        txtIdCajero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCajeros = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdSupervisor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (2).png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(620, 470, 62, 48);

        txtIdCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCajeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCajero);
        txtIdCajero.setBounds(130, 470, 130, 24);

        jLabel1.setText("(Solo apto al Modificar o Actualizar)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 500, 210, 16);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(50, 190, 170, 24);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 170, 110, 16);

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula);
        txtCedula.setBounds(280, 130, 170, 24);

        jLabel3.setText("Cédula:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 110, 110, 16);

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(510, 130, 170, 24);

        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 110, 110, 16);

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(280, 190, 170, 24);

        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 170, 110, 16);

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(510, 190, 170, 24);

        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 170, 110, 16);

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(50, 250, 170, 24);

        jLabel7.setText("Dirección:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 230, 110, 16);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(280, 250, 170, 24);

        jLabel8.setText("Usuario:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 230, 110, 16);

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(510, 250, 170, 24);

        jLabel9.setText("Contraseña:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 230, 110, 16);

        tblCajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCajeros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(13, 303, 700, 150);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscando-en-la-tierra.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(380, 470, 62, 48);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-flexible.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(320, 470, 62, 48);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ajustes.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(440, 470, 62, 48);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goma-de-borrar.png"))); // NOI18N
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(500, 470, 62, 48);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(560, 470, 62, 48);

        jLabel10.setText("Id del Supervisor:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 110, 110, 16);

        txtIdSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSupervisorActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdSupervisor);
        txtIdSupervisor.setBounds(50, 130, 170, 24);

        jLabel12.setText("id cajero:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 470, 70, 16);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_registrar3.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 730, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu obj= new Menu();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtIdCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCajeroActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        //   ***** Buscar *****
        
        // Abro la conexion con la Base de Datos
        objConexion.conexion();
        
        // Creo el modelo para del JTable
        DefaultTableModel modelo = (DefaultTableModel) tblCajeros.getModel();
        // Defino un vector para el cargue del JTable
        String vector[] = new String[10];
               
        // Limpio el JTable antes del cargue
        modelo.setColumnCount(0);
        modelo.setNumRows(0);
        
        // Cargo las columnas de titulo al Jtable
        modelo.addColumn("CÓDIGO");
        modelo.addColumn("CÓDIGO SUP");
        modelo.addColumn("CEDULA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("CORREO");
        modelo.addColumn("DIRECCIÓN");
        modelo.addColumn("TELÉFONO");
        modelo.addColumn("USUARIO");
        modelo.addColumn("CONTRASEÑA");
        
        try{
             ResultSet rs = objConexion.leer("SELECT `id_cajero`, `id_cajero_supervisor`, `cedula`, `nombre`, `apellido`, `correo`, `direccion`, `telefono`, `usuario`, `contraseña` FROM `cajero`");
            while(rs.next()){
                // Cargo el vector con los valores de la fila a cargar en el JTabl
                vector[0] = String.valueOf(rs.getInt("id_cajero"));
                vector[1] = rs.getString("id_cajero_supervisor");
                vector[2] = rs.getString("cedula");
                vector[3] = rs.getString("nombre"); 
                vector[4] = rs.getString("apellido"); 
                vector[5] = rs.getString("correo"); 
                vector[6] = rs.getString("direccion");
                vector[7] = rs.getString("telefono");
                vector[8] = rs.getString("usuario");
                vector[9] = rs.getString("contraseña");
                // Adiciono la fila al JTable
                modelo.addRow(vector);                 
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        // Cierro la conexión con la Base de Datos
        objConexion.desconectar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // *** Defino las variables ***
        int idSupervisor;
        int cedula;
        String nombre;
        String apellido;
        String correo;
        String direccion;
        String telefono;
        String usuario;
        String contraseña;
        
        if(txtIdSupervisor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el Id del Supervisor.");
            txtIdSupervisor.requestFocus();
            return;
        } 

        if(txtCedula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la cedula.");
            txtCedula.requestFocus();
            return;
        } 

        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre.");
            txtNombre.requestFocus();
            return;
        } 
        
        if(txtApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el apellido.");
            txtApellido.requestFocus();
            return;
        } 
        
        if(txtCorreo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el correo.");
            txtCorreo.requestFocus();
            return;
        }
        
        if(txtDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la dirección.");
            txtDireccion.requestFocus();
            return;
        }
        
        if(txtTelefono.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el telefono.");
            txtTelefono.requestFocus();
            return;
        }
        
        if(txtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el usuario.");
            txtUsuario.requestFocus();
            return;
        }
        
        if(txtContraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la contraseña.");
            txtContraseña.requestFocus();
            return;
        } 
         
         // *** Asigno los elementos gráficos a las variables ***
        idSupervisor = Integer.parseInt(txtIdSupervisor.getText());
        cedula = Integer.parseInt(txtCedula.getText());
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        correo = txtCorreo.getText();
        direccion = txtDireccion.getText();
        telefono = txtTelefono.getText();
        usuario = txtUsuario.getText();
        contraseña = txtContraseña.getText();
        
       
        // *** Realizo los procesos ***
        
        // Abro la conexion con la Base de Datos
        objConexion.conexion();

        try{
            // Busco el ultimo registro de la tabla y lo incremento en 1
            ResultSet rs = objConexion.leer("SELECT MAX(id_cajero) FROM cajero");
            // Traigo el siguiente registro
            rs.next();
            
            // Inserto el registro en la tabla
            boolean respuesta = objConexion.consultar("INSERT INTO cajero (`id_cajero_supervisor`, `cedula`, `nombre`, `apellido`, `correo`, `direccion`, `telefono`, `usuario`, `contraseña`) VALUES('"+idSupervisor+"','"+cedula+"','"+nombre+"','"+apellido+"','"+correo+"','"+direccion+"','"+telefono+"','"+usuario+"','"+contraseña+"') ");
            
            // Imprimo el mensaje para indicar si se guardo o no el registro
            if(respuesta == true){                
                JOptionPane.showMessageDialog(null,"Su registro se guardo con éxito.");
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR: No se pudo guardar el registro.");
            } 
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        // *** Limpio los Campos ***   
        txtIdSupervisor.setText("");
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtIdCajero.setText("");
        
        // Cierro la conexión con la Base de Datos
        objConexion.desconectar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtIdSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSupervisorActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        // *** Defino las variables ***
        int idCajero;
        int idSupervisor;
        int cedula;
        String nombre;
        String apellido;
        String correo;
        String direccion;
        String telefono;
        String usuario;
        String contraseña;
        
        if(txtIdCajero.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el Id del Cajero a modificar.");
            txtIdCajero.requestFocus();
            return;
        } 
        
        if(txtIdSupervisor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el Id del Supervisor.");
            txtIdSupervisor.requestFocus();
            return;
        } 

        if(txtCedula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la cedula.");
            txtCedula.requestFocus();
            return;
        } 

        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre.");
            txtNombre.requestFocus();
            return;
        } 
        
        if(txtApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el apellido.");
            txtApellido.requestFocus();
            return;
        } 
        
        if(txtCorreo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el correo.");
            txtCorreo.requestFocus();
            return;
        }
        
        if(txtDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la dirección.");
            txtDireccion.requestFocus();
            return;
        }
        
        if(txtTelefono.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el telefono.");
            txtTelefono.requestFocus();
            return;
        }
        
        if(txtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el usuario.");
            txtUsuario.requestFocus();
            return;
        }
        
        if(txtContraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la contraseña.");
            txtContraseña.requestFocus();
            return;
        } 
         
         // *** Asigno los elementos gráficos a las variables ***
        idCajero = Integer.parseInt(txtIdCajero.getText());
        idSupervisor = Integer.parseInt(txtIdSupervisor.getText());
        cedula = Integer.parseInt(txtCedula.getText());
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        correo = txtCorreo.getText();
        direccion = txtDireccion.getText();
        telefono = txtTelefono.getText();
        usuario = txtUsuario.getText();
        contraseña = txtContraseña.getText();
        
       
        // *** Realizo los procesos ***
        
        // Abro la conexion con la Base de Datos
        objConexion.conexion();

        try{           
            // Modifico el registro en la tabla
            boolean respuesta = objConexion.consultar("UPDATE `cajero` SET `id_cajero_supervisor`='"+idSupervisor+"',`cedula`='"+cedula+"',`nombre`='"+nombre+"',`apellido`='"+apellido+"',`correo`='"+correo+"',`direccion`='"+direccion+"',`telefono`='"+telefono+"',`usuario`='"+usuario+"',`contraseña`='"+contraseña+"' WHERE id_cajero='"+idCajero+"'");
            
            // Imprimo el mensaje para indicar si se guardo o no el registro
            if(respuesta == true){                
                JOptionPane.showMessageDialog(null,"Su registro se guardo con éxito.");
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR: No se pudo guardar el registro.");
            } 
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        // *** Limpio los Campos ***   
        txtIdSupervisor.setText("");
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtIdCajero.setText("");
        
        // Cierro la conexión con la Base de Datos
        objConexion.desconectar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // Defino el modelo para el JTable
        DefaultTableModel modelo = (DefaultTableModel) tblCajeros.getModel();        

        // Abro la conexión con la Base de Datos
        try{
            objConexion.conexion();

            // Asigno el indice del elemento seleccionado 
            indice = tblCajeros.getSelectedRow();                   

            // Asigno a idCiudad el elemento a eliminar
            int idCajero =  Integer.parseInt((String)modelo.getValueAt(indice, 0));        

            // Elimino el registro del JTable
            modelo.removeRow(indice);

            // Elimino el registro de la tabla ciudad
            boolean respuesta = objConexion.consultar("DELETE FROM cajero WHERE id_cajero = '"+idCajero+"' ");

            // Imprimo el mensaje para indicar si se eliminó o no el registro
            if(respuesta == true){
               JOptionPane.showMessageDialog(null, "El registro se elimino.");
            }
            else{
               JOptionPane.showMessageDialog(null, "ERROR: No se elimino el registro.");
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        // *** Limpio los Campos ***   
        txtIdSupervisor.setText("");
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtIdCajero.setText("");

        // Limpio las filas y las columnas de la tabla
        modelo.setColumnCount(0);
        modelo.setNumRows(0);      
        
        // Cierro la conexión a la Base de Datos
        objConexion.desconectar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tblCajeros.getModel();
        
        txtIdSupervisor.setText("");
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtIdCajero.setText("");
        
        modelo.setColumnCount(0);
        modelo.setNumRows(0); 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEmpleado().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCajeros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCajero;
    private javax.swing.JTextField txtIdSupervisor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    BaseDeDatos mysql=new BaseDeDatos();
    Connection cn = mysql.Connectar();
}

